### ISSUE TITLE
possibly non-working enchant?

### ISSUE THREAD

**Issue by ramcq** [flathub/org.gnome.gitg#5]
Does GtkSpell actually work correctly in this app? I'm just working on something else that bundled enchant 1 and searching for examples on Flathub - I found that it does not find the dictionaries unless you set the myspell path to find the hunspell dictionaries in the runtime. For an example, see the older GNOME runtimes - https://gitlab.gnome.org/GNOME/gnome-sdk-images/blob/gnome-3-28/org.gnome.Sdk.json.in#L565

**Comment by albfan** [comment]
Is completely possible. We added enchant because it was missing on new GNOME runtimes

https://gitlab.gnome.org/GNOME/gitg/commit/04309f63b6a9675e05d475c5ef06f993a19ad114

and we still need enchant 1 for GtkSpell https://gitlab.gnome.org/GNOME/gitg/issues/120

Will test this on master an 3.30 branch and update here.

Thanks for reporting

**Comment by albfan** [comment]
Looks to me that this is working

![Captura de pantalla de 2020-10-11 10-39-01](https://user-images.githubusercontent.com/220968/95674236-256cc600-0baf-11eb-8725-8ef96894c9e7.png)
